version: '3.8'
services:
  db:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_USER=pure
      - POSTGRES_PASSWORD=secret
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
#      - ./db/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

volumes:
  db:
    driver: local
